//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myprint.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrintingEntities : DbContext
    {
        public PrintingEntities()
            : base("name=PrintingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OrderMonth> tb_order_month { get; set; }
        public virtual DbSet<OrderYear> tb_order_year { get; set; }
        public virtual DbSet<PrintOrder> tb_print_order { get; set; }
        public virtual DbSet<User> tb_user { get; set; }
        public virtual DbSet<OrderDay> tb_order_day { get; set; }
    }
}
