//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myprint.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PrintOrder
    {
        [ScaffoldColumn(false)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long id { get; set; }
        public string user_name { get; set; }
        public string user_qq { get; set; }
        public string user_wxchat { get; set; }
        public string user_phone { get; set; }
        public string print_file_name { get; set; }
        public Nullable<int> prinf_number { get; set; }
        public Nullable<int> paper_number { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<double> total_amount { get; set; }
        public string note { get; set; }
        public string order_status { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
    }
}
